### ISSUE TITLE
Bulid errors mingw

### ISSUE THREAD

**Issue by todirbg** [skiselkov/libacfutils#10]
Hi,
there are few build errors that bug me and I will appreciate some help :)

First when running build_deps there is error about geographiclib

```
/usr/bin/install: 'GeographicLib/Config.h' and '/home/todir/Downloads/GitHub/libacfutils/geographiclib/geographiclib-win-64/include/GeographicLib/Config.h' are the same file
make[2]: *** [Makefile:406: install-nobase_includeHEADERS] Error 1
make[2]: Leaving directory '/home/todir/Downloads/GitHub/libacfutils/geographiclib/geographiclib-win-64/include'
make[1]: *** [Makefile:527: install-am] Error 2
make[1]: Leaving directory '/home/todir/Downloads/GitHub/libacfutils/geographiclib/geographiclib-win-64/include'
make: *** [Makefile:484: install-recursive] Error 1
```

then when running build_redist there are 2 errors
The first one is that mingw can not find <fontconfig/fontconfig.h> and as expected it is not in /usr/x86_64-w64-mingw32/include folder. Copying the one from usr/include fixes that, but I think it is wrong to do it that way. Any idea how to fix it?
The second one is:

```
In file included from ../src/acfutils/types.h:26,
                 from ../src/acfutils/sysmacros.h:33,
                 from ../src/acfutils/log.h:24,
                 from ../src/acfutils/assert.h:32,
                 from ../src/mt_cairo_render.c:35:
../src/acfutils/core.h:44:25: error: redefinition of ‘struct __libacfutils_stat’
   44 | #define ACFSYM(__sym__) __libacfutils_ ## __sym__
      |                         ^~~~~~~~~~~~~~
../src/acfutils/core.h:44:25: note: originally defined here
   44 | #define ACFSYM(__sym__) __libacfutils_ ## __sym__
      |                         ^~~~~~~~~~~~~~
../src/acfutils/core.h:44:25: note: in definition of macro ‘ACFSYM’
   44 | #define ACFSYM(__sym__) __libacfutils_ ## __sym__
      |                         ^~~~~~~~~~~~~~
../src/acfutils/helpers.h:472:8: note: in expansion of macro ‘stat’
  472 | struct stat {
      |        ^~~~
../src/acfutils/core.h:44:25: error: conflicting types for ‘__libacfutils_stat’
   44 | #define ACFSYM(__sym__) __libacfutils_ ## __sym__
      |                         ^~~~~~~~~~~~~~
../src/acfutils/core.h:44:25: note: previous declaration of ‘__libacfutils_stat’ was here
   44 | #define ACFSYM(__sym__) __libacfutils_ ## __sym__
      |                         ^~~~~~~~~~~~~~
../src/acfutils/core.h:44:25: note: in definition of macro ‘ACFSYM’
   44 | #define ACFSYM(__sym__) __libacfutils_ ## __sym__
      |                         ^~~~~~~~~~~~~~
../src/acfutils/helpers.h:477:16: note: in expansion of macro ‘stat’
  477 | API_EXPORT int stat(const char *pathname, struct stat *buf);
      |                ^~~~
make[1]: *** [Makefile.Debug:1123: debug/mt_cairo_render.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/todir/Downloads/GitHub/libacfutils/qmake'
make: *** [Makefile:45: debug] Error 2
```
Those errors are for mingw only. It compiles fine for linux only with build-win-lin -l
I am on ubuntu 21.04 with mingw gcc version 10-win32 20210408 (GCC)

**Comment by JT8D-17** [comment]
On Arch, I managed to build cairo (and other packages) by adding 
> autoreconf -i "$SRCDIR"

to build_dep.common at around line 83, i.e.

> 	if ! [ -d "$SRCDIR" ]; then
...
fi
>
>autoreconf -i "$SRCDIR"
>
>if [ -f "$BUILDDIR/$PRODFILE" ] && \
...

This increases compilation time somewhat, but it seems to fix a lot of compilation errors using Mingw.

**Comment by JT8D-17** [comment]
Getting the same "redefinition" error now.
From what I could find out, MingW seems to be choking on the "stat" variable name because it's interpreting it as the "static definition". I've tried to fix this by renaming "stat" to "stat2" and then doing the same in helpers.c and chart_prov_common.c, but it's there that the compiler chokes for good.

**Comment by JT8D-17** [comment]
Compiles fine on my other system though. Both run Arch Linux on AMD CPUs at the same package level. Very weird.

**Comment by todirbg** [comment]
I have installed ubuntu 18.04 in a VM and everything compiled fine. Still got the geographiclib error but it does not stop the compilation and I don't see any issues. Also this resolved some other issues I had with OpenWXR and OpenGPWS builds.

Closing this issue now. Apparently it is about MinGW version changes.
@skiselkov  please tell us what versions of mingw and gcc are you using for your builds? 10x
