### ISSUE TITLE
Libxml build error

### ISSUE THREAD

**Issue by JT8D-17** [skiselkov/libacfutils#13]
On both the Windows and Linux builds.

>../libxml2-2.9.4/runtest.c: In function ‘streamProcessTest’:
../libxml2-2.9.4/runtest.c:2145:65: warning: unused parameter ‘options’ [-Wunused-parameter]
 2145 |                   xmlTextReaderPtr reader, const char *rng, int options) {
      |                                                             ~~~~^~~~~~~
  CC       testlimits.o
sed -e 's?\@XML_LIBDIR\@?-L/media/Data/Git_Repos/libacfutils/libxml2/libxml2-linux-64/lib?g' \
    -e 's?\@XML_INCLUDEDIR\@?-I/media/Data/Git_Repos/libacfutils/libxml2/libxml2-linux-64/include/libxml2?g' \
    -e 's?\@VERSION\@?2.9.4?g' \
    -e 's?\@XML_LIBS\@?-lxml2      -lm ?g' \
       < ../libxml2-2.9.4/xml2Conf.sh.in > xml2Conf.tmp \
&& mv xml2Conf.tmp xml2Conf.sh
  CCLD     testdso.la
  CC       testapi.o
cc1: fatal error: testapi.c: No such file or directory
compilation terminated.

Newer versions from Github do not build either because the do not come with a configure script/file.

OS: Arch Linux

**Comment by JT8D-17** [comment]
Solved by adding `autoreconf -i "$SRCDIR"` at around line 83 in build_dep.common. And maybe by updating the libxml source package to the latest release.

See here: https://github.com/skiselkov/libacfutils/issues/10#issuecomment-891196772

**Comment by todirbg** [comment]
10x it worked :)
On my last attempt the build_deps gave the error about geographiclib install, but the build continued. Build_redist failed with error about missing pixman lib. I tried running the build_cairo_deps, but it failed. Then I added the line in build_dep.common and ran build_cairo_deps again with no errors this time. Also I ran build_geographiclib again and than build_redist worked with no errors.

**Comment by JT8D-17** [comment]
I've since opened a fork that implements selective autoconfiguration into `build_dep.common`. It's geared toward my Arch Linux installation (and some mingw system packages), but some of the other stuff can be extracted for local use.
https://github.com/JT8D-17/libacfutils
