### ISSUE TITLE
Outdated beta XP SDK

### ISSUE THREAD

**Issue by KSI65** [skiselkov/libacfutils#22]
The SDK version in this package looks like an old beta version dated from last year when XP12 itself was in beta. There is a newer version 4.0.1 released earlier this year.
[XPSDK401.zip](https://github.com/skiselkov/libacfutils/files/12030421/XPSDK401.zip)

**Comment by joecise** [comment]
> The SDK version in this package looks like an old beta version dated from last year when XP12 itself was in beta. There is a newer version 4.0.1 released earlier this year.
> [XPSDK401.zip](https://github.com/skiselkov/libacfutils/files/12030421/XPSDK401.zip)

Updates in https://github.com/skiselkov/libacfutils/commit/e9e221aeeea23817a14fdc44e7383aa9b5f240a6

**Comment by pilsnerish** [comment]
Updates in https://github.com/skiselkov/libacfutils/commit/e9e221aeeea23817a14fdc44e7383aa9b5f240a6

**Comment by KSI65** [comment]
Thanks.
