### ISSUE TITLE
GCC 12 warns about possible integer overflow in safe_strdup

### ISSUE THREAD

**Issue by todirbg** [skiselkov/libacfutils#28]
Hi I got this build error:
``In file included from /usr/include/string.h:535,
                 from ../src/airportdb.c:24:
In function ‘memcpy’,
    inlined from ‘safe_strdup’ at ../src/acfutils/safe_alloc.h:187:2,
    inlined from ‘parse_apt_dat_1_line’ at ../src/airportdb.c:894:21,
    inlined from ‘read_apt_dat’ at ../src/airportdb.c:1557:11:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:10: error: ‘__builtin_memcpy’ pointer overflow between offset 0 and size 18446744073709551615 [-Werror=array-bounds]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
``
Fixed it by changing "int l" to "size_t l" in safe_strdup function. Linux xubuntu 22.04 gcc 12.3.0

**Comment by skiselkov** [comment]
Fixed in commit f6e6091.
