### ISSUE TITLE
function conf_write is not writing in the conf file

### ISSUE THREAD

**Issue by olivierbutler** [skiselkov/libacfutils#34]
**
 * Writes a conf_t object to a file. Returns B_TRUE if the write was
 * successful, B_FALSE otherwise.
 */
bool_t
conf_write(const conf_t *conf, FILE *fp)
{
	return (conf_write_impl(conf, fp, 0, B_FALSE, B_FALSE));   <-- Last arg should be B_FALSE and not B_TRUE
}

**Comment by skiselkov** [comment]
:pray:
Fixed in commit [92064da](https://github.com/skiselkov/libacfutils/commit/92064da4f82261c0028c8d3f3805d35da2b238f7).
