### ISSUE TITLE
widget.c : font_face not initialized. When calling tt_render_cb() .. crashing on Linux

### ISSUE THREAD

**Issue by olivierbutler** [skiselkov/libacfutils#36]
tt_render_cb() .. crashing on Linux and may not crash by chance on other platform

tooltip_set_new_native(XPLMWindowID window) is not initializing tts->font_face.
cairo_set_font_face(cr, tts->font_face) will crash if unluckily tts->font_face is not null

proposal :

`tooltip_set_t *
tooltip_set_new_native(XPLMWindowID window)
{
	int left, top, right, bottom;
	cairo_text_extents_t te;

	tooltip_set_t *tts = safe_malloc(sizeof (*tts));
	tts->window = window;
	list_create(&tts->tooltips, sizeof (tooltip_t),
	    offsetof(tooltip_t, node));
	list_insert_tail(&tooltip_sets, tts);
	XPLMGetWindowGeometry(window, &left, &top, &right, &bottom);
	tts->orig_w = right - left;
	tts->orig_h = top - bottom;
	tts->display_delay = DEFAULT_DISPLAY_DELAY;
	tts->surf = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, 1, 1);
	tts->cr = cairo_create(tts->surf);
	tts->font_size = TT_FONT_SIZE;
	tts->font_face = NULL;                                       <---  NULL = default font face
	cairo_set_font_size(tts->cr, tts->font_size);
	memcpy(tts->bg_color, (double[4]){TT_BACKGROUND_RGBA},
	    sizeof (tts->bg_color));
	cairo_text_extents(tts->cr, "X", &te);
	tts->line_height = te.height * TT_LINE_HEIGHT_MULT;

	return (tts);
}
`

**Comment by skiselkov** [comment]
Fixed in commit 67d78ea.
